### ISSUE TITLE
Not sure if these are bugs or lack of documentation.  Trouble using 1.12 version

### ISSUE THREAD

**Issue by Lothrazar** [Corosauce/MovePlus#2]
Sideways dodge jumping works great ..... but i dont know how to do wall jumping, i jump into vertical cobblestone and jump again and, nothing. 

 

Same with double jump i dont understand how it works, i push jump in midair and nothing happens

 

I checked your coros website as well

 

And the Z keybinding is not on the key controls.

Also this page does not document any blocks being added, but theres a red recharge block and a yellow block being added and i dont know how to disable them.

**Comment by Corosauce** [comment]
The features between old versions and 1.12.2 versions are very different, see the curse page on latest info: [https://minecraft.curseforge.com/projects/move-plus](https://minecraft.curseforge.com/projects/move-plus)

Basically all the features you're having issues with dont exist in the 1.12 version.
